"""Updated Company Table

Revision ID: 01d29b0672ca
Revises: 73640f588b9d
Create Date: 2023-08-09 07:16:19.265786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d29b0672ca'
down_revision = '73640f588b9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dev_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_companies_dev_id_devs'), 'devs', ['dev_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_companies_dev_id_devs'), type_='foreignkey')
        batch_op.drop_column('dev_id')

    # ### end Alembic commands ###
