"""Updated Company Table

Revision ID: 2a77a1146fea
Revises: 8848b7559c2d
Create Date: 2023-08-09 06:46:55.212804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a77a1146fea'
down_revision = '8848b7559c2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
