"""Updated Company Table

Revision ID: 73640f588b9d
Revises: 2a77a1146fea
Create Date: 2023-08-09 06:54:21.920975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73640f588b9d'
down_revision = '2a77a1146fea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_devs_company_id_companies'), 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_devs_company_id_companies'), type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
