"""Updated Company Table

Revision ID: 8848b7559c2d
Revises: 3243e4519884
Create Date: 2023-08-09 06:43:04.564952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8848b7559c2d'
down_revision = '3243e4519884'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
