"""Updated Company Table

Revision ID: ae4d2678b12c
Revises: c2d71ca82314
Create Date: 2023-08-09 07:27:55.701875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae4d2678b12c'
down_revision = 'c2d71ca82314'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
