"""Updated Company Table

Revision ID: c2d71ca82314
Revises: 01d29b0672ca
Create Date: 2023-08-09 07:22:17.469239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d71ca82314'
down_revision = '01d29b0672ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
